# .github/workflows/upload-report.yml
#
# Manual GitHub Actions workflow for generating and uploading reports to Dropbox
# using dropbox_uploader with refresh-token authentication + uv.

name: Generate and Upload Report

on:
  # ❌ No schedule — only manual trigger
  workflow_dispatch:
    inputs:
      destination_folder:
        description: 'Dropbox destination folder'
        required: false
        default: '/Reports/Automated'

env:
  PYTHON_VERSION: '3.11'
  DROPBOX_FOLDER: ${{ github.event.inputs.destination_folder || '/Reports/Automated' }}

jobs:
  generate-and-upload:
    if: false  # Temporarily disable this job  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        run: pip install uv

      - name: Create uv environment and install dependencies
        run: uv sync

      - name: Generate report
        id: generate
        run: |
          # Your report generation script
          uv run python your_report_script.py

          # Find latest report file
          REPORT_FILE=$(ls -t report_*.md 2>/dev/null | head -n 1)

          if [ -z "$REPORT_FILE" ]; then
            echo "Error: No report file generated"
            exit 1
          fi

          echo "report_file=$REPORT_FILE" >> "$GITHUB_OUTPUT"
          echo "Generated report: $REPORT_FILE"

      - name: Upload to Dropbox
        id: upload
        env:
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          DROPBOX_FOLDER: ${{ env.DROPBOX_FOLDER }}
        run: |
          uv run python -m dropbox_uploader \
            "${{ steps.generate.outputs.report_file }}" \
            --folder "$DROPBOX_FOLDER" \
            --verbose

      - name: Report status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Report successfully uploaded to Dropbox"
          else
            echo "❌ Report upload failed"
          fi
