# .github/workflows/upload-report.yml
#
# Example GitHub Actions workflow for generating and uploading reports to Dropbox.
# 
# Setup:
# 1. Add your DROPBOX_ACCESS_TOKEN to repository secrets
#    (Settings → Secrets and variables → Actions → New repository secret)
#
# 2. Copy this file to .github/workflows/upload-report.yml in your repository
#
# 3. Adjust the schedule and script paths as needed

name: Generate and Upload Report

on:
  # Run on a schedule (adjust as needed)
  schedule:
    - cron: '0 8 * * *'  # Daily at 8:00 AM UTC
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      destination_folder:
        description: 'Dropbox destination folder'
        required: false
        default: '/Reports/Automated'

env:
  PYTHON_VERSION: '3.11'
  DROPBOX_FOLDER: ${{ github.event.inputs.destination_folder || '/Reports/Automated' }}

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dropbox
          # If you have a requirements.txt:
          # pip install -r requirements.txt
      
      - name: Generate report
        id: generate
        run: |
          # Run your report generation script
          # This should create a markdown file with timestamp in the name
          python your_report_script.py
          
          # Find the generated file (adjust pattern as needed)
          REPORT_FILE=$(ls -t report_*.md 2>/dev/null | head -n1)
          
          if [ -z "$REPORT_FILE" ]; then
            echo "Error: No report file generated"
            exit 1
          fi
          
          echo "report_file=$REPORT_FILE" >> $GITHUB_OUTPUT
          echo "Generated report: $REPORT_FILE"
      
      - name: Upload to Dropbox
        id: upload
        env:
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        run: |
          python -m dropbox_uploader "${{ steps.generate.outputs.report_file }}" \
            --folder "${{ env.DROPBOX_FOLDER }}" \
            --verbose
      
      - name: Report status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Report successfully uploaded to Dropbox"
          else
            echo "❌ Report upload failed"
          fi


  # Alternative job using the Python API directly
  generate-and-upload-python:
    runs-on: ubuntu-latest
    if: false  # Disabled by default - enable by changing to 'true'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        run: |
          pip install dropbox
      
      - name: Generate and upload
        env:
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          DROPBOX_FOLDER: ${{ env.DROPBOX_FOLDER }}
        run: |
          python << 'EOF'
          import os
          from datetime import datetime
          from dropbox_uploader import upload_file
          
          # Generate report
          timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M")
          filename = f"report_{timestamp}.md"
          
          # Your report generation logic here
          content = f"# Report {timestamp}\n\nGenerated by GitHub Actions"
          with open(filename, "w") as f:
              f.write(content)
          
          # Upload
          folder = os.environ.get("DROPBOX_FOLDER", "/Reports")
          path = upload_file(filename, dropbox_folder=folder)
          print(f"Uploaded to: {path}")
          EOF
